spring:
  cloud:
    gateway:
# spring.cloud.gateway.routes
      routes:
      - id: api-service
        uri: http://localhost:10002
        predicates:
          - Path=/pirates/**
      - id: product-service
        uri: http://localhost:10001
        predicates:
          - Path=/products/**
